import IUT1.SymmetryCore
import Mathlib.Algebra.Group.Units.Equiv
import Lean.Elab.Tactic.Omega

/-!
# IUT1-I1-SYM-001: sign-orbit bridge

This copy-on-write extension implements only T05a--T05d.  It keeps the abstract
carrier, its distinguished orbit of charts, the transported involution, and the
quotient as separate types.  It contains no affine group, torsor, poly-action,
or geometric identification.
-/

namespace IUT1

universe u v

/-- C01: the natural number denoted by `l±` in the bounded contract. -/
def lPlusMinus (l : ℕ) : ℕ := (l + 1) / 2

/-- C01-only alias correcting the historical name without assigning C05 to T02. -/
theorem T02_C01_neg_eq_self_iff (l : ℕ) [Fact l.Prime] (hl5 : 5 ≤ l) (x : Fl l) :
    -x = x ↔ x = 0 :=
  T02_C01_C05_neg_eq_self_iff l hl5 x

/-- A type equipped with a specified involutive equivalence. -/
structure SignInvolution (E : Type u) where
  neg : E ≃ E
  involutive : Function.Involutive neg

/-- The two-point-orbit relation generated by an involution. -/
def SignInvolution.setoid {E : Type u} (S : SignInvolution E) : Setoid E where
  r x y := y = x ∨ y = S.neg x
  iseqv := {
    refl := fun _ ↦ Or.inl rfl
    symm := by
      intro x y h
      rcases h with h | h
      · exact Or.inl h.symm
      · exact Or.inr <| by
          calc
            x = S.neg (S.neg x) := (S.involutive x).symm
            _ = S.neg y := by rw [h]
    trans := by
      intro x y z hxy hyz
      rcases hxy with hxy | hxy <;> rcases hyz with hyz | hyz
      · exact Or.inl (hyz.trans hxy)
      · exact Or.inr (hyz.trans (congrArg S.neg hxy))
      · exact Or.inr (hyz.trans hxy)
      · exact Or.inl (hyz.trans ((congrArg S.neg hxy).trans (S.involutive x)))
  }

/-- Quotient of a type by the relation generated by its specified involution. -/
abbrev SignQuotient {E : Type u} (S : SignInvolution E) := Quotient S.setoid

/-- The quotient class of an element under a specified involution. -/
def signClass {E : Type u} (S : SignInvolution E) (x : E) : SignQuotient S :=
  Quotient.mk S.setoid x

/-- The sign involution on the finite-field coordinate type. -/
def flSignInvolution (l : ℕ) : SignInvolution (Fl l) where
  neg := Equiv.neg (Fl l)
  involutive := neg_neg

/-- C05: the additive coordinate quotient; it is not the multiplicative label group. -/
abbrev AdditiveSignOrbit (l : ℕ) := SignQuotient (flSignInvolution l)

/-- Equivariance for maps between types with specified sign involutions. -/
def SignEquivariant {E : Type u} {F : Type v}
    (S : SignInvolution E) (T : SignInvolution F) (φ : E ≃ F) : Prop :=
  ∀ x, φ (S.neg x) = T.neg (φ x)

/-- General quotient descent with both well-definedness directions proved. -/
def signDescendEquiv {E : Type u} {F : Type v}
    (S : SignInvolution E) (T : SignInvolution F) (φ : E ≃ F)
    (hφ : SignEquivariant S T φ) : SignQuotient S ≃ SignQuotient T where
  toFun := Quotient.map φ <| by
    intro a b hab
    rcases hab with hab | hab
    · exact Or.inl (congrArg φ hab)
    · exact Or.inr ((congrArg φ hab).trans (hφ a))
  invFun := Quotient.map φ.symm <| by
    intro a b hab
    rcases hab with hab | hab
    · exact Or.inl (congrArg φ.symm hab)
    · exact Or.inr <| by
        apply φ.injective
        calc
          φ (φ.symm b) = b := φ.apply_symm_apply b
          _ = T.neg a := hab
          _ = T.neg (φ (φ.symm a)) := by simp
          _ = φ (S.neg (φ.symm a)) := (hφ (φ.symm a)).symm
  left_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro x
    apply Quotient.sound
    exact Or.inl (φ.symm_apply_apply x).symm
  right_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro x
    apply Quotient.sound
    exact Or.inl (φ.apply_symm_apply x).symm

/-!
`source_id=SRC-OFFICIAL-7360E3ED27C235B5`.
Definition 6.1(i), printed p. 155 supplies the orbit-of-charts role;
Definition 6.4(i), printed p. 162 supplies the quotient-index role.
Epistemic status: `DERIVED_COORDINATIZED_MODEL`.
Discriminant: both quotient maps require relation-respect proofs; no descended
equivalence is accepted as input data.
-/
def T05a_C05_descendEquiv {E : Type u} {F : Type v}
    (S : SignInvolution E) (T : SignInvolution F) (φ : E ≃ F)
    (hφ : SignEquivariant S T φ) : SignQuotient S ≃ SignQuotient T :=
  signDescendEquiv S T φ hφ

/-- Postcomposition of a chart by coordinate negation. -/
def postNegChart {E : Type u} (l : ℕ) (φ : E ≃ Fl l) : E ≃ Fl l :=
  φ.trans (Equiv.neg (Fl l))

/-- The involution on a carrier transported through a coordinate chart. -/
def transportedSign {E : Type u} {l : ℕ} (φ : E ≃ Fl l) : SignInvolution E where
  neg := φ.trans ((Equiv.neg (Fl l)).trans φ.symm)
  involutive := by
    intro x
    simp

/-!
The structure contains exactly a carrier type, a nonempty distinguished chart
orbit, and an exact membership law for the two postcomposition representatives.
It contains no cardinality, descended equivalence, or target conclusion.
-/
structure SignedLabelCarrier (l : ℕ) where
  E : Type u
  chartOrbit : Set (E ≃ Fl l)
  orbit_nonempty : chartOrbit.Nonempty
  orbit_exact : ∀ φ, φ ∈ chartOrbit → ∀ ψ,
    ψ ∈ chartOrbit ↔ ψ = φ ∨ ψ = postNegChart l φ

noncomputable section

/-- A selected representative used internally; the structure stores only its nonempty orbit. -/
def SignedLabelCarrier.baseChart {l : ℕ} (C : SignedLabelCarrier.{u} l) : C.E ≃ Fl l :=
  Classical.choose C.orbit_nonempty

private theorem SignedLabelCarrier.baseChart_mem {l : ℕ}
    (C : SignedLabelCarrier.{u} l) : C.baseChart ∈ C.chartOrbit :=
  Classical.choose_spec C.orbit_nonempty

/-- The carrier involution transported from an arbitrary selected orbit representative. -/
def SignedLabelCarrier.signInvolution {l : ℕ} (C : SignedLabelCarrier.{u} l) :
    SignInvolution C.E :=
  transportedSign C.baseChart

/-- The abstract carrier quotient by its transported sign involution. -/
abbrev SignedLabelCarrier.SignOrbit {l : ℕ} (C : SignedLabelCarrier.{u} l) :=
  SignQuotient C.signInvolution

private theorem SignedLabelCarrier.chart_equivariant {l : ℕ}
    (C : SignedLabelCarrier.{u} l) (φ : C.E ≃ Fl l) (hφ : φ ∈ C.chartOrbit) :
    SignEquivariant C.signInvolution (flSignInvolution l) φ := by
  rcases (C.orbit_exact C.baseChart C.baseChart_mem φ).mp hφ with h | h
  · subst φ
    intro x
    simp [SignedLabelCarrier.signInvolution, transportedSign, flSignInvolution]
  · subst φ
    intro x
    simp [SignedLabelCarrier.signInvolution, transportedSign, flSignInvolution,
      postNegChart]

/-- The quotient equivalence induced by a chart in the distinguished orbit. -/
def SignedLabelCarrier.descend {l : ℕ} (C : SignedLabelCarrier.{u} l)
    (φ : C.E ≃ Fl l) (hφ : φ ∈ C.chartOrbit) :
    C.SignOrbit ≃ AdditiveSignOrbit l :=
  T05a_C05_descendEquiv C.signInvolution (flSignInvolution l) φ
    (C.chart_equivariant φ hφ)

private theorem SignedLabelCarrier.postNeg_mem {l : ℕ}
    (C : SignedLabelCarrier.{u} l) (φ : C.E ≃ Fl l) (hφ : φ ∈ C.chartOrbit) :
    postNegChart l φ ∈ C.chartOrbit :=
  (C.orbit_exact φ hφ (postNegChart l φ)).mpr (Or.inr rfl)

/-!
`source_id=SRC-OFFICIAL-7360E3ED27C235B5`.
Definition 6.1(i), printed p. 155 supplies the representative change inside the
chart orbit; Definition 6.4(i), printed p. 162 supplies the descended quotient
map. Epistemic status: `DERIVED_COORDINATIZED_MODEL`.
Discriminant: equality is extensional both on the transported involution and on
quotient classes; no cardinality coincidence is used.
-/
theorem T05b_C05_postNeg_invariance {l : ℕ} (C : SignedLabelCarrier.{u} l)
    (φ : C.E ≃ Fl l) (hφ : φ ∈ C.chartOrbit) :
    (transportedSign (postNegChart l φ)).neg = (transportedSign φ).neg ∧
      C.descend (postNegChart l φ) (C.postNeg_mem φ hφ) = C.descend φ hφ := by
  constructor
  · apply Equiv.ext
    intro x
    simp [transportedSign, postNegChart]
  · apply Equiv.ext
    intro q
    refine Quotient.inductionOn q ?_
    intro x
    change signClass (flSignInvolution l) (-(φ x)) =
      signClass (flSignInvolution l) (φ x)
    apply Quotient.sound
    exact Or.inr (by simp [flSignInvolution])

/-- Closed T05c carrier, definitionally distinct from `Fl 5`. -/
def T05CounterCarrier : Type := ULift (Fl 5)

/-- Base chart on the closed T05c carrier. -/
def t05CounterBaseChart : T05CounterCarrier ≃ Fl 5 :=
  Equiv.ulift

/-- Multiplication by two as a coordinate permutation of `Fl 5`. -/
def t05CounterTimesTwo : Fl 5 ≃ Fl 5 :=
  (ZMod.unitOfCoprime 2 (by decide : Nat.Coprime 2 5)).mulLeft

/-- Rival sign-equivariant chart for the closed countermodel. -/
def t05CounterDoubleChart : T05CounterCarrier ≃ Fl 5 :=
  t05CounterBaseChart.trans t05CounterTimesTwo

/-- Sign involution on the closed countermodel carrier. -/
def t05CounterSign : SignInvolution T05CounterCarrier :=
  transportedSign t05CounterBaseChart

private theorem t05CounterBase_equivariant :
    SignEquivariant t05CounterSign (flSignInvolution 5) t05CounterBaseChart := by
  intro x
  simp [t05CounterSign, transportedSign, t05CounterBaseChart, flSignInvolution]

private theorem t05CounterDouble_equivariant :
    SignEquivariant t05CounterSign (flSignInvolution 5) t05CounterDoubleChart := by
  intro x
  simp [t05CounterSign, transportedSign, t05CounterDoubleChart, t05CounterBaseChart,
    t05CounterTimesTwo, flSignInvolution]

/-- Descended base chart in the closed T05c countermodel. -/
def t05CounterBaseDescend : SignQuotient t05CounterSign ≃ AdditiveSignOrbit 5 :=
  T05a_C05_descendEquiv t05CounterSign (flSignInvolution 5) t05CounterBaseChart
    t05CounterBase_equivariant

/-- Descended rival chart in the closed T05c countermodel. -/
def t05CounterDoubleDescend : SignQuotient t05CounterSign ≃ AdditiveSignOrbit 5 :=
  T05a_C05_descendEquiv t05CounterSign (flSignInvolution 5) t05CounterDoubleChart
    t05CounterDouble_equivariant

/-- The class of one used as the closed T05c discriminating witness. -/
def t05CounterWitness : SignQuotient t05CounterSign :=
  signClass t05CounterSign (ULift.up (1 : Fl 5))

private theorem t05Class_one_ne_two :
    signClass (flSignInvolution 5) (1 : Fl 5) ≠
      signClass (flSignInvolution 5) (2 : Fl 5) := by
  intro h
  have hrel := Quotient.exact h
  change ((2 : Fl 5) = 1 ∨ (2 : Fl 5) = -(1 : Fl 5)) at hrel
  rcases hrel with hrel | hrel
  · exact (by decide : (2 : Fl 5) ≠ 1) hrel
  · exact (by decide : (2 : Fl 5) ≠ -(1 : Fl 5)) hrel

/-!
`source_id=SRC-OFFICIAL-7360E3ED27C235B5`.
Definition 6.1(i), printed p. 155 supplies the distinguished-orbit criterion;
Definition 6.4(i), printed p. 162 supplies the quotient-index comparison.
Epistemic status: `DISCRIMINANT_COUNTERMODEL`, not a source theorem.
Discriminant: on the definitionally distinct carrier `ULift (Fl 5)`, the base
chart and multiplication-by-two chart commute with sign, are not related by
postcomposition with `±1`, and send the class of one to distinct quotient
classes.
-/
theorem T05c_C05_closed_countermodel :
    SignEquivariant t05CounterSign (flSignInvolution 5) t05CounterBaseChart ∧
    SignEquivariant t05CounterSign (flSignInvolution 5) t05CounterDoubleChart ∧
    t05CounterDoubleChart ≠ t05CounterBaseChart ∧
    t05CounterDoubleChart ≠ postNegChart 5 t05CounterBaseChart ∧
    t05CounterDoubleDescend t05CounterWitness ≠
      t05CounterBaseDescend t05CounterWitness ∧
    t05CounterDoubleDescend ≠ t05CounterBaseDescend := by
  refine ⟨t05CounterBase_equivariant, t05CounterDouble_equivariant, ?_, ?_, ?_, ?_⟩
  · intro h
    have hw := congrArg (fun e : T05CounterCarrier ≃ Fl 5 ↦
      e (ULift.up (1 : Fl 5))) h
    have : (2 : Fl 5) = 1 := by
      simpa [t05CounterDoubleChart, t05CounterBaseChart, t05CounterTimesTwo] using hw
    exact (by decide : (2 : Fl 5) ≠ 1) this
  · intro h
    have hw := congrArg (fun e : T05CounterCarrier ≃ Fl 5 ↦
      e (ULift.up (1 : Fl 5))) h
    have : (2 : Fl 5) = -(1 : Fl 5) := by
      simpa [t05CounterDoubleChart, t05CounterBaseChart, t05CounterTimesTwo,
        postNegChart] using hw
    exact (by decide : (2 : Fl 5) ≠ -(1 : Fl 5)) this
  · intro h
    apply t05Class_one_ne_two
    have := h.symm
    simpa [t05CounterDoubleDescend, t05CounterBaseDescend, t05CounterWitness,
      T05a_C05_descendEquiv, signDescendEquiv, signClass, t05CounterDoubleChart,
      t05CounterBaseChart, t05CounterTimesTwo] using this
  · intro h
    have hw := congrArg (fun e : SignQuotient t05CounterSign ≃ AdditiveSignOrbit 5 ↦
      e t05CounterWitness) h
    apply t05Class_one_ne_two
    have := hw.symm
    simpa [t05CounterDoubleDescend, t05CounterBaseDescend, t05CounterWitness,
      T05a_C05_descendEquiv, signDescendEquiv, signClass, t05CounterDoubleChart,
      t05CounterBaseChart, t05CounterTimesTwo] using this

/-- The smaller natural representative of a sign class. -/
def signRepresentative {l : ℕ} (x : Fl l) : ℕ :=
  min x.val (-x).val

private theorem signRepresentative_neg {l : ℕ} (x : Fl l) :
    signRepresentative (-x) = signRepresentative x := by
  simp [signRepresentative, min_comm]

section PrimeAtLeastFive

variable (l : ℕ) [Fact l.Prime]

local instance : NeZero l :=
  ⟨(Fact.out : Nat.Prime l).pos.ne'⟩

private theorem signRepresentative_lt_lPlusMinus (hl5 : 5 ≤ l) (x : Fl l) :
    signRepresentative x < lPlusMinus l := by
  unfold lPlusMinus
  have hl2 : l ≠ 2 := by
    intro h
    subst l
    omega
  have hodd : Odd l := (Fact.out : Nat.Prime l).odd_of_ne_two hl2
  obtain ⟨k, hk⟩ := hodd
  by_cases hx : x = 0
  · subst x
    simp [signRepresentative]
    omega
  · have hxpos : 0 < x.val := ZMod.val_pos.mpr hx
    have hxlt : x.val < l := x.val_lt
    rw [signRepresentative, ZMod.neg_val]
    simp only [if_neg hx]
    by_cases hle : x.val ≤ l - x.val
    · rw [min_eq_left hle]
      omega
    · rw [min_eq_right (Nat.le_of_not_ge hle)]
      omega

/-- Canonical finite representative of a coordinate sign class. -/
def signRepresentativeFin (hl5 : 5 ≤ l) (x : Fl l) : Fin (lPlusMinus l) :=
  ⟨signRepresentative x, signRepresentative_lt_lPlusMinus l hl5 x⟩

private theorem signRepresentativeFin_respects (hl5 : 5 ≤ l) {x y : Fl l}
    (hxy : (flSignInvolution l).setoid.r x y) :
    signRepresentativeFin l hl5 x = signRepresentativeFin l hl5 y := by
  apply Fin.ext
  rcases hxy with hxy | hxy
  · subst y
    rfl
  · subst y
    change signRepresentative x = signRepresentative (-x)
    exact (signRepresentative_neg x).symm

/-- Explicit equivalence between additive sign classes and canonical representatives. -/
def additiveSignOrbitEquivFin (hl5 : 5 ≤ l) :
    AdditiveSignOrbit l ≃ Fin (lPlusMinus l) where
  toFun := Quotient.lift (signRepresentativeFin l hl5)
    (fun _ _ h ↦ signRepresentativeFin_respects l hl5 h)
  invFun := fun i ↦ signClass (flSignInvolution l) (i.val : Fl l)
  left_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro x
    change signClass (flSignInvolution l) (signRepresentative x : Fl l) =
      signClass (flSignInvolution l) x
    apply Quotient.sound
    change x = (signRepresentative x : Fl l) ∨
      x = -(signRepresentative x : Fl l)
    by_cases hle : x.val ≤ (-x).val
    · left
      rw [signRepresentative, min_eq_left hle]
      exact (ZMod.natCast_zmod_val x).symm
    · right
      rw [signRepresentative, min_eq_right (Nat.le_of_not_ge hle),
        ZMod.natCast_zmod_val]
      simp
  right_inv := by
    intro i
    apply Fin.ext
    change signRepresentative (i.val : Fl l) = i.val
    have hl2 : l ≠ 2 := by
      intro h
      subst l
      omega
    have hodd : Odd l := (Fact.out : Nat.Prime l).odd_of_ne_two hl2
    obtain ⟨k, hk⟩ := hodd
    have hilt : i.val < l := by
      have := i.isLt
      unfold lPlusMinus at this
      omega
    have hval : ((i.val : Fl l).val) = i.val := ZMod.val_natCast_of_lt hilt
    by_cases hi0 : i.val = 0
    · simp [signRepresentative, hi0]
    · have hcast : (i.val : Fl l) ≠ 0 := by
        intro hz
        apply hi0
        have hzval : ((i.val : Fl l).val) = (0 : Fl l).val := congrArg ZMod.val hz
        rw [hval] at hzval
        simpa using hzval
      rw [signRepresentative, hval, ZMod.neg_val]
      simp only [if_neg hcast]
      rw [hval, min_eq_left]
      have := i.isLt
      unfold lPlusMinus at this
      omega

/-!
`source_id=SRC-OFFICIAL-7360E3ED27C235B5`.
Definition 6.1(i), printed p. 155 supplies the chart-orbit structure;
Definition 6.4(i), printed p. 162 supplies the abstract quotient and its stated
size role; section I1, printed p. 3 supplies the notation `lPlusMinus`.
Epistemic status: `DERIVED_FROM_T05a_AND_FINITE_ORBIT_COUNT`.
Discriminant: the prototype count is derived through canonical representatives
and transported through T05a; neither cardinality nor descended equivalence is a
field or hypothesis of `SignedLabelCarrier`.
-/
theorem T05d_C01_C05_card_sign_orbits (hl5 : 5 ≤ l) :
    Nat.card (AdditiveSignOrbit l) = lPlusMinus l ∧
      ∀ C : SignedLabelCarrier.{u} l, Nat.card C.SignOrbit = lPlusMinus l := by
  have hprototype : Nat.card (AdditiveSignOrbit l) = lPlusMinus l := by
    simpa using Nat.card_congr (additiveSignOrbitEquivFin l hl5)
  refine ⟨hprototype, ?_⟩
  intro C
  calc
    Nat.card C.SignOrbit = Nat.card (AdditiveSignOrbit l) :=
      Nat.card_congr (C.descend C.baseChart C.baseChart_mem)
    _ = lPlusMinus l := hprototype

end PrimeAtLeastFive

end

end IUT1
