import Mathlib.Algebra.Field.ZMod
import Mathlib.Data.Nat.Totient
import Mathlib.Data.ZMod.Basic
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.Coset.Card
import Mathlib.GroupTheory.OrderOfElement

/-!
# IUT1-I1-SYM-001: finite symmetry core

This module implements only the first bounded campaign T01--T04.  It models the
finite field, the sign subgroup of its unit group, and the multiplicative label
quotient.  It makes no geometric identification and contains no later-campaign
affine, torsor, or poly-action construction.
-/

namespace IUT1

/-- C01: the finite-field carrier used by the source notation. -/
abbrev Fl (l : ℕ) := ZMod l

/-- C01: the natural number denoted by `l*` in the bounded contract. -/
def lStar (l : ℕ) : ℕ := (l - 1) / 2

/-- C02: the subgroup of units generated by the sign `-1`. -/
def SignSubgroup (l : ℕ) : Subgroup (ZMod l)ˣ :=
  Subgroup.zpowers (-1)

/-- C02: the multiplicative unit-label group modulo sign. -/
abbrev MultiplicativeLabelGroup (l : ℕ) :=
  (ZMod l)ˣ ⧸ SignSubgroup l

section Prime

variable (l : ℕ) [Fact l.Prime]

local instance : NeZero l :=
  ⟨(Fact.out : Nat.Prime l).pos.ne'⟩

/-- T01 [C01]: the field carrier has exactly `l` elements. -/
theorem T01_C01_card_Fl : Fintype.card (Fl l) = l :=
  ZMod.card l

/-- T02 [C01, C05]: for prime `l >= 5`, sign has no nonzero fixed point. -/
theorem T02_C01_C05_neg_eq_self_iff (hl5 : 5 ≤ l) (x : Fl l) :
    -x = x ↔ x = 0 := by
  have htwo : (2 : Fl l) ≠ 0 := by
    intro hzero
    have hdiv : l ∣ 2 := (ZMod.natCast_eq_zero_iff 2 l).mp hzero
    have hle : l ≤ 2 := Nat.le_of_dvd (by decide) hdiv
    exact (Nat.not_lt_of_ge hle) (lt_of_lt_of_le (by decide : 2 < 5) hl5)
  constructor
  · intro hneg
    have hsum : x + x = 0 := add_eq_zero_iff_eq_neg.mpr hneg.symm
    have hmul : (2 : Fl l) * x = 0 := by
      simpa [two_mul] using hsum
    exact (mul_eq_zero.mp hmul).resolve_left htwo
  · rintro rfl
    simp

/-- T03 [C02]: the subgroup generated by sign has cardinality two. -/
theorem T03_C02_card_SignSubgroup (hl5 : 5 ≤ l) :
    Nat.card (SignSubgroup l) = 2 := by
  have hl2 : l ≠ 2 := by
    intro h
    subst l
    exact (by decide : ¬ 5 ≤ 2) hl5
  rw [SignSubgroup, Nat.card_zpowers, ← orderOf_units, Units.coe_neg_one,
    orderOf_neg_one, ringChar.eq (ZMod l) l, if_neg hl2]

/-- T04 [C02, C04]: the multiplicative label quotient has cardinality `(l-1)/2`. -/
theorem T04_C02_C04_card_MultiplicativeLabelGroup (hl5 : 5 ≤ l) :
    Nat.card (MultiplicativeLabelGroup l) = lStar l := by
  change Nat.card ((ZMod l)ˣ ⧸ SignSubgroup l) = (l - 1) / 2
  have hlagrange : Nat.card (ZMod l)ˣ =
      Nat.card ((ZMod l)ˣ ⧸ SignSubgroup l) * Nat.card (SignSubgroup l) :=
    Subgroup.card_eq_card_quotient_mul_card_subgroup (SignSubgroup l)
  have hunits : Nat.card (ZMod l)ˣ = l - 1 := by
    rw [Nat.card_eq_fintype_card]
    exact (Nat.prime_iff_card_units l).mp (Fact.out : Nat.Prime l)
  have hsign : Nat.card (SignSubgroup l) = 2 :=
    T03_C02_card_SignSubgroup l hl5
  rw [hunits, hsign] at hlagrange
  exact Nat.eq_div_of_mul_eq_right (by decide) (by
    simpa [Nat.mul_comm] using hlagrange.symm)

end Prime

end IUT1
