import IUT1.SymmetryCore
import IUT1.SignOrbitBridge
import IUT1.SignedAffineCore
import IUT1.SignedAffineDihedral

/-!
# Reading T01--T11 without being a Lean specialist

This file is a pedagogical facade over the reviewed core.  It does not replace
the proofs and does not introduce new source claims.  Each section states what
the corresponding target means, instantiates it at `l = 5`, and points out the
nearby interpretation that the example is intended to reject.

Lean notation used below:

* `Fact (Nat.Prime l)` carries the assumption that `l` is prime.
* `Fintype.card X` or `Nat.card X` is the number of elements of a finite type.
* `ZMod l` is the ring of integers modulo `l`.
* `↔` means logical equivalence and `∧` means conjunction.
-/

namespace IUT1.Tutorial

/-! ## T01: the coordinate field has `l` elements

`Fl l` is a readable project name for `ZMod l`.  T01 records its carrier size.
The theorem is elementary, but it fixes the coordinate type used by all later
targets.  The closed example is five-element arithmetic, not an IUT claim.
-/
theorem T01_example_l5 : Fintype.card (Fl 5) = 5 := by
  letI : Fact (Nat.Prime 5) := ⟨by decide⟩
  exact T01_C01_card_Fl 5

/-! ## T02: negation has no nonzero fixed point

For odd prime modulus, `x = -x` forces `2*x = 0`, hence `x = 0`.  The explicit
lower bound `5 ≤ l` is the source context adopted by this unit.  At modulus two
the statement would be false because `1 = -1`.
-/
theorem T02_example_l5 (x : Fl 5) : -x = x ↔ x = 0 := by
  letI : Fact (Nat.Prime 5) := ⟨by decide⟩
  simpa using T02_C01_C05_neg_eq_self_iff 5 (by decide) x

/-! ## T03: the sign subgroup has two elements

Inside the units of `ZMod l`, the subgroup generated by `-1` is exactly the
two-element sign subgroup when `l ≥ 5` is prime.
-/
theorem T03_example_l5 : Nat.card (SignSubgroup 5) = 2 := by
  letI : Fact (Nat.Prime 5) := ⟨by decide⟩
  simpa using T03_C02_card_SignSubgroup 5 (by decide)

/-! ## T04: nonzero labels modulo sign

There are `l-1` nonzero residues.  Pairing every unit `x` with `-x` leaves
`(l-1)/2` classes.  This quotient does not contain the zero class.
-/
theorem T04_example_l5 : Nat.card (MultiplicativeLabelGroup 5) = 2 := by
  letI : Fact (Nat.Prime 5) := ⟨by decide⟩
  simpa [lStar] using
    T04_C02_C04_card_MultiplicativeLabelGroup 5 (by decide)

/-! ## T05: charts, sign quotients, and independence of representative

T05 is deliberately split into four obligations in `SignOrbitBridge.lean`:

1. an equivariant chart descends to the quotients;
2. changing a distinguished chart by postcomposition with negation leaves the
   descended map unchanged;
3. a closed five-element countermodel shows why "all equivariant charts" is
   too large a replacement for the distinguished source orbit;
4. the additive sign quotient has `(l+1)/2` classes, including the zero class.

The following executable count separates the additive quotient (three classes)
from T04's multiplicative quotient (two classes).
-/
theorem T05_example_l5_additive_sign_orbits :
    Nat.card (AdditiveSignOrbit 5) = 3 := by
  letI : Fact (Nat.Prime 5) := ⟨by decide⟩
  have h := (T05d_C01_C05_card_sign_orbits.{0} 5 (by decide)).1
  simpa [lPlusMinus] using h

/-! ## T06: the visible semidirect product

A signed-affine element has translation `a` and a Boolean sign `s`.  The value
`false` means `+1`; `true` means `-1`.  Multiplication is derived from function
composition:

`(a,s) * (b,t) = (a + signAct s b, xor s t)`.

For `g=(1,-)` and `h=(2,+)` modulo five, the translation is `1-2=4`, not
`1+2=3`.  That single computation rejects the direct-product mutation.
-/
theorem T06_example_l5_visible_law :
    let g : SignedAffine 5 := ⟨1, true⟩
    let h : SignedAffine 5 := ⟨2, false⟩
    g * h = ⟨4, true⟩ ∧ (g * h).translation ≠ 3 :=
  T06_example_l5_semidirect

/-! ## T07: multiplication and affine action use the same convention

The product `g*h` means "apply `h` first, then `g`".  With the T06 elements and
`z=3`, both `act (g*h) z` and `act g (act h z)` evaluate to one.  Reversing the
composition order gives a different closed value and fails this regression.
-/
theorem T07_example_l5_composition :
    let g : SignedAffine 5 := ⟨1, true⟩
    let h : SignedAffine 5 := ⟨2, false⟩
    let z : Fl 5 := 3
    (g * h).act z = 1 ∧ g.act (h.act z) = 1 :=
  T07_example_l5_action_order

/-! ## T08: cardinality of the signed-affine group

The carrier is visibly `Fl l × Bool`, hence it has `l*2 = 2*l` elements.  At
`l=5` this is ten, whereas the additive sign quotient from T05 has three
classes.  Equal-looking sign notation therefore cannot justify identifying the
two types.
-/
theorem T08_example_l5_signed_affine_card :
    Fintype.card (SignedAffine 5) = 10 :=
  T08_example_l5_card

theorem T08_example_l5_not_sign_orbit_card :
    (10 : ℕ) ≠ lPlusMinus 5 ∧ lPlusMinus 5 = 3 := by
  decide

/-! ## A second worked model: `l = 7`

The seven-element model exercises the generic T04--T08 results and provides the
second half of the independently reviewed T11 regression suite.
-/

theorem T04_example_l7 : Nat.card (MultiplicativeLabelGroup 7) = 3 := by
  letI : Fact (Nat.Prime 7) := ⟨by decide⟩
  simpa [lStar] using
    T04_C02_C04_card_MultiplicativeLabelGroup 7 (by decide)

theorem T05_example_l7_additive_sign_orbits :
    Nat.card (AdditiveSignOrbit 7) = 4 := by
  letI : Fact (Nat.Prime 7) := ⟨by decide⟩
  have h := (T05d_C01_C05_card_sign_orbits.{0} 7 (by decide)).1
  simpa [lPlusMinus] using h

theorem T06_example_l7_semidirect :
    let g : SignedAffine 7 := ⟨2, true⟩
    let h : SignedAffine 7 := ⟨5, false⟩
    g * h = ⟨4, true⟩ ∧ (g * h).translation ≠ 0 := by
  decide

theorem T07_example_l7_composition :
    let g : SignedAffine 7 := ⟨2, true⟩
    let h : SignedAffine 7 := ⟨5, false⟩
    let z : Fl 7 := 6
    (g * h).act z = 5 ∧ g.act (h.act z) = 5 := by
  decide

theorem T08_example_l7_signed_affine_card :
    Fintype.card (SignedAffine 7) = 14 := by
  letI : Fact (Nat.Prime 7) := ⟨by decide⟩
  simpa using T08_C06_card_signedAffine 7

theorem T08_example_l7_not_sign_orbit_card :
    (14 : ℕ) ≠ lPlusMinus 7 ∧ lPlusMinus 7 = 4 := by
  decide

/-! ## T09: the translations are a normal index-two subgroup

The condition `negative = false` picks out ordinary translations.  The element
`(0,true)` is a reflection.  Multiplying on the right by it changes the sign bit,
so it swaps translations and reflections.  This gives exactly two cosets;
normality is then a theorem about index-two subgroups, not a stored assumption.
-/
theorem T09_example_l5_visible_cosets :
    let q : SignedAffine 5 := ⟨0, true⟩
    q ∉ translationSubgroup 5 ∧
      ∀ g : SignedAffine 5,
        (g * q ∈ translationSubgroup 5) ↔ g ∉ translationSubgroup 5 :=
  T09_example_l5_reflection_toggle

/-! ## T10: comparison with Mathlib's dihedral group

The equivalence is proved after both groups exist independently.  Mathlib writes
rotations as `r a` and reflections as `sr a`.  With its multiplication
convention, the signed pair `(a,true)` must map to `sr (-a)`.  At modulus five,
the correct image of `(1,true)` sends `2` to `4`; the tempting but wrong image
`sr 1` sends it to `2`.
-/
theorem T10_example_l5_visible_sign_choice :
    let g : SignedAffine 5 := ⟨1, true⟩
    let z : Fl 5 := 2
    dihedralAct (signedAffineDihedralEquiv 5 g) z = 4 ∧
      g.act z = 4 ∧ dihedralAct (DihedralGroup.sr 1) z = 2 :=
  T10_example_l5_action_discriminant

/-! ## T11: two complete cardinality regressions

The vectors below deliberately retain three different types.  Their entries are
the multiplicative label quotient, the additive sign-orbit quotient, and the
signed-affine group.  Equal source notation would not justify identifying them.
-/
theorem T11_example_l5_vector :
    Nat.card (MultiplicativeLabelGroup 5) = 2 ∧
      Nat.card (AdditiveSignOrbit 5) = 3 ∧
      Fintype.card (SignedAffine 5) = 10 :=
  T11_l5_cardinality_vector

theorem T11_example_l7_vector :
    Nat.card (MultiplicativeLabelGroup 7) = 3 ∧
      Nat.card (AdditiveSignOrbit 7) = 4 ∧
      Fintype.card (SignedAffine 7) = 14 :=
  T11_l7_cardinality_vector

end IUT1.Tutorial
